In [ ]:
a=10
print("I am ",a," years old")

I am  10  years old


In [ ]:

#arthimetic operation on two numbers
a=int(input("enter a value:"))
b=int(input("enter b value:"))
print("sum is ",a+b)
print("difference is ",b-a)
print("multiply is ",a*b)
print("Quotient is ",a/b)
print("remainder is ",a%b)
print("power is ",a**b)
print("floor div is ",a//b)

enter a value:2
enter b value:2
sum is  4
difference is  0
multiply is  4
Quotient is  1.0
remainder is  0
power is  4
floor div is  1


In [ ]:
#take the number from the user salary.if the is more than 50k there is 10% tax.print his final salary
salary=float(input("enter salary:"))
if(salary>=50000):
    a=(10/100)*salary
    print("10% tax is ",a," \n the total salary is ",salary-a)
else:
    print("no tax.salary is ",salary)

enter salary:50000
10% tax is  5000.0  
 the total salary is  45000.0


In [ ]:
#get the salary from the user if the salary is more than or equal to 50k .apply 10% tax dection.if the salary is less than 50k apply 5% tax.if the salary is more than 70k apply 12% tax.if the salary exceeds 100k.print your promoted to next level
salary=float(input("enter salary:"))
if(salary>=100000):
    print("you are promoted to next level","\n final salary is ", salary)
elif(salary>=70000):
    print("your salary is ",salary," so 12% tax applied \n the final salary is ",salary-((12/100)*salary))
elif(salary>=50000):
    print("your salary is ",salary," so 10% tax applied\n the final salary is ",salary-((10/100)*salary))
elif(salary>0 and salary<50000):
    print("your salary is less than 50k"," so 5% tax applied \n the final salary is ",salary-((5/100)*salary))

enter salary:64000
your salary is  64000.0  so 10% tax applied
 the final salary is  57600.0


In [ ]:
#creating tables using for loop
a=int(input("enter table:"))
b=int(input("enter no.of steps:"))
for i in range(1,b+1):
    print(a,"x",i,"=",a*i)

enter table:5
enter no.of steps:20
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50
5 x 11 = 55
5 x 12 = 60
5 x 13 = 65
5 x 14 = 70
5 x 15 = 75
5 x 16 = 80
5 x 17 = 85
5 x 18 = 90
5 x 19 = 95
5 x 20 = 100


In [ ]:
#creating table with while loop
a=int(input("enter table:"))
b=int(input("enter no.of steps:"))
i=1
while(i<=b):
   print(a,"x",i,"=",a*i)
   i=i+1

In [ ]:

#appending element in list
L1=[2,"web",43,"chat",6.2,True]
L1.append(45) #insert at end in list
print(L1)

[2, 'web', 43, 'chat', 6.2, True, 45]


In [ ]:
#insering the element into list
L1=[2,"web",43,"chat",6.2,True]
L1.insert(2,64) #insert at position in list 2 be the index,64 be the element
print(L1)

[2, 'web', 64, 43, 'chat', 6.2, True]


In [ ]:
#extend list 1 with list 2
L1=[2,"web",43,"chat",6.2,True]
L2=['apple','banana']
L1.extend(L2) # merge second lists elements into first list
print(L1)

[2, 'web', 43, 'chat', 6.2, True, 'apple', 'banana']


In [ ]:
#remove element in list
L1=[2,"web",43,"chat",6.2,True]
L1.remove(43) #remove element in list
print(L1)

[2, 'web', 'chat', 6.2, True]


In [ ]:
#pop element in list
L1=[2,"web",43,"chat",6.2,True]
L1.pop(2) #pop element using the index num in list
print(L1)

[2, 'web', 'chat', 6.2, True]


In [ ]:
#clear element in list
L1=[2,"web",43,"chat",6.2,True]
L1.clear() #clear the list and return empty list
print(L1)

[]


In [ ]:
#create a list of 10 integer elements.print their squares.same these square in new list
L1=[12,14,56,17,95,48,70,89,23,52]
L2=[]
L2=[i*i for i in L1 if i>50]
#L2=[i*i if i>50 else 'x' for i in L1]
'''for i in L1:
   L2.append(i*i)'''
print(L2)

[3136, 9025, 4900, 7921, 2704]


In [ ]:
#take the salary from the user if salary is less than 50k 10% tax otherwise 15%
L1=[23000,20000,56000,43000,72000,100000]
L2=[i-0.1*i if i<50000 else i-i*0.15 for i in L1]
print(L2)

[20700.0, 18000.0, 47600.0, 38700.0, 61200.0, 85000.0]


In [ ]:
#creating dictionary
dict ={23:'tiger',34:'lion',35:'cheetha',48:'dear'}
print(dict)
print(dict.keys())
print(dict.values())
print(dict[23])

{23: 'tiger', 34: 'lion', 35: 'cheetha', 48: 'dear'}
dict_keys([23, 34, 35, 48])
dict_values(['tiger', 'lion', 'cheetha', 'dear'])
tiger


In [ ]:
dict={"dept":"cse", 'details':{"year":"II",'sec':'D','count':71}}
print(dict["details"]["year"])
print(dict["details"]["sec"])
print(dict["details"]["count"])

II
D
71


In [ ]:
#create dictionary using two lists
L1=[2,3,4,5,6]
L2=[4,9,16,25,36]
dic1=dict(zip(L1,L2))
print(dic1)

{2: 4, 3: 9, 4: 16, 5: 25, 6: 36}


In [ ]:
#numpy using create 1d array
import numpy as np
A=np.array([1,2,3,4]) #1d array
print(A.ndim)
print(A.shape)
print(A)

1
(4,)
[1 2 3 4]


In [ ]:

#2d array creation
import numpy as np
A=np.array([[2,3,4],[5,6,7],[8,9,10]])
#elements in each row = column
print(A.ndim)
print(A.shape)
print(A)

2
(3, 3)
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
import numpy as np
A=np.array([[[1,2],[2,3],[3,4]],[[4,5],[5,6],[6,8]]])
print(A.ndim)
print(A.shape)
print(A)

3
(2, 3, 2)
[[[1 2]
  [2 3]
  [3 4]]

 [[4 5]
  [5 6]
  [6 8]]]


In [ ]:
#creating two dimension array using ones((row,col)) function
import numpy as np
A=np.zeros((2,4))
print(A)
B=np.ones((2,3,4))
print(B)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:

#all diagonals as 1 and remain 0 using eye() function
import numpy as np
A=np.eye(4)
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#create rows and columns using arange function
import numpy as np
A=np.arange(1,10,2) #start,stop,step
print(A)
print(type(A))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [ ]:
#print all the numbers are divisible by 8 using arange function b/w 1 to 1000
import numpy as np
A=np.arange(8,1001,8)
print(A)

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [ ]:
#linspace- splitting the range into n numbers having common difference
import numpy as np
A=np.linspace(3,2,12)
print(A)

[3.         2.90909091 2.81818182 2.72727273 2.63636364 2.54545455
 2.45454545 2.36363636 2.27272727 2.18181818 2.09090909 2.        ]


In [ ]:
#creating tuple
A=('apple','banana','orange','grapes')
B=('apple',12,True,45.4)
print(A)
print(B)

('apple', 'banana', 'orange', 'grapes')
('apple', 12, True, 45.4)


In [ ]:
#accessing tuple
A=('apple','banana','graph',45,True,45,7)
print(A[0])
print(A[1])
print(A[2])
print(A[3])
print(A[4])
print(A[5])

apple
banana
graph
45
True
45


In [ ]:
#accessing tuple
A=(2,3,5,7,9,0)
print(A[-1])
print(A[0:4])
print(A[-4:-1])

0
(2, 3, 5, 7)
(5, 7, 9)


In [ ]:
#print tuples using for loop
A=(1,2,3,4,6)
for i in A:
    print(i)

1
2
3
4
6


In [ ]:
#length of tuple
A=(9,4,23,56)
print(len(A)) #length function
print(type(A)) #type of A

4
<class 'tuple'>


In [ ]:
#adding values into tuple
#tuple convert into list and add elements and again list us conver into tuple
A=(1,2,3,4,5)
B=list(A)
B.append(10)
C=list(B)
print(C)

[1, 2, 3, 4, 5, 10]


In [ ]:
#tuple operations
A=(1,2,3)
B=(4,5,6)
C=A+B #concate
print(C)
print(A*2) #tuple A elements are again add in same tuple
print(len(A)) #length of tuple
print(3 in A) #checking if element is present in the tuple

(1, 2, 3, 4, 5, 6)
(1, 2, 3, 1, 2, 3)
3
True


In [ ]:
 #functions in tuple
A=(1,2,3)
B=(4,5,6)
print(min(A)) #minimum value in tuple A
print(max(B)) #maximum value in tuple B

1
6


In [ ]:
#creating set
A={1,2,3,4}
print(A)

{1, 2, 3, 4}


In [ ]:
#add and remove new elements in set
A={1,2,3,4}
A.add(10)
print(A)
A.pop() #this function is pop first element in set
A.remove(4) #this removes specific element
print(A)

{1, 2, 3, 4, 10}
{2, 3, 10}


In [ ]:
#difference b/w sets
A={1,2,3,4}
B={3,4,5,6}
C=A.difference(B)
print(C)

{1, 2}


In [ ]:
#intersection
A={1,2,3,4,5}
B={4,5,2,7,8}
C=A.intersection(B)
print(C)

{2, 4, 5}


In [ ]:
#update the set with another set
A={1,2,3,6}
B={3,4}
C=B.update(A)
print(C)

None


In [ ]:
#union
A={1,2,3,4}
B={5,7,2,9}
C=A.union(B)
print(C)

{1, 2, 3, 4, 5, 7, 9}
