In [ ]:
#sort in list
a=[2,23,12,45,13,7]
a.sort()
print(a)

[2, 7, 12, 13, 23, 45]


In [ ]:

#reshape this using arange of numbers
import numpy as np
A=np.arange(1,13).reshape(3,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:

#sorted in list
a=[12,7,14,56,13]
b=sorted(a)
print(b)

[7, 12, 13, 14, 56]


In [ ]:

#reshape this using linspace
import numpy as np
A=np.linspace(4,8,10).reshape(5,2)
print(A)

[[4.         4.44444444]
 [4.88888889 5.33333333]
 [5.77777778 6.22222222]
 [6.66666667 7.11111111]
 [7.55555556 8.        ]]


In [ ]:
A=np.array([4,76,89,13,24,35,64,29]).reshape(2,2,2)
print(A)

[[[ 4 76]
  [89 13]]

 [[24 35]
  [64 29]]]


In [ ]:

#resize
A=np.array([4,76,89,75,64,23,90,82])
A.resize(2,2,2) #changes the shape of orginal array
#resize- changes needs savings in another variable
print(A)

[[[ 4 76]
  [89 75]]

 [[64 23]
  [90 82]]]


In [ ]:

#subtract two numpy arrays
A=np.array([34,56,78,90])
B=np.array([7,9,3,10])
C=A-B
print(A-B)
#print(C)

[27 47 75 80]


In [ ]:

#add two numpy arrays
A=np.array([1,2,3,4])
B=np.array([1,2,3,4])
C=A+B
print(C)

[2 4 6 8]


In [ ]:
#memory multiply two numpy arrays
import numpy as np
A=np.array([1,2,2,4]).reshape(2,2)
B=np.array([1,2,3,4]).reshape(2,2)
C=A*B #memory multiplication
print(C)

[[ 1  4]
 [ 6 16]]


In [ ]:
#matrix multiply two numpy arrays
import numpy as np
A=np.array([1,2,2,4]).reshape(2,2)
B=np.array([1,2,3,4]).reshape(2,2)
C=A@B #matrix multiplication
print(C)

[[ 7 10]
 [14 20]]


In [ ]:
#find Max and min in numpy arrays
A=np.array([2,65,12,45,94,74])
print(A.max()) #max and min only excepts numeric values
print(A.min())

94
2


In [ ]:
#print Max and min in matrixs in numpy
A=np.array([34,25,43,78]).reshape(2,2)
print(A.max(axis=0)) #axis=0 - it prints Max number in every column in matrix
print(A.max(axis=1)) #axis=1 - it prints Max number in every row in matrix

[43 78]
[34 78]


In [ ]:

#joining the arrays matrix
#vstack,hstack
import numpy as np
A=np.array([1,2,3,4]).reshape(2,2)
B=np.array([1,2,3,4]).reshape(2,2)
print(np.vstack((A,B))) #print verically stacking the array matrix
print(np.hstack((A,B))) #prints horizontally stacking the array matrix
print(np.stack((A,B),axis=0))

[[1 2]
 [3 4]
 [1 2]
 [3 4]]
[[1 2 1 2]
 [3 4 3 4]]
[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


In [ ]:

#dstack
A=np.arange(60).reshape(2,5,6)
print(A)
print(np.dstack(A)) #no.of rows -> no.of groups

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]]

 [[30 31 32 33 34 35]
  [36 37 38 39 40 41]
  [42 43 44 45 46 47]
  [48 49 50 51 52 53]
  [54 55 56 57 58 59]]]
[[[ 0 30]
  [ 1 31]
  [ 2 32]
  [ 3 33]
  [ 4 34]
  [ 5 35]]

 [[ 6 36]
  [ 7 37]
  [ 8 38]
  [ 9 39]
  [10 40]
  [11 41]]

 [[12 42]
  [13 43]
  [14 44]
  [15 45]
  [16 46]
  [17 47]]

 [[18 48]
  [19 49]
  [20 50]
  [21 51]
  [22 52]
  [23 53]]

 [[24 54]
  [25 55]
  [26 56]
  [27 57]
  [28 58]
  [29 59]]]


In [ ]:
#splitting arrays matrix
import numpy as np
A=np.arange(36).reshape(6,6)
print(A)
#np.vsplit(A,3)
np.vsplit(A,(2,5)) #it splits vertically
#np.hsplit(A,3)
#np.hsplit(A,(1,2)) #it splits horizontally

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34, 35]])]

In [ ]:

#argmax
A=np.linspace(18,5,18).reshape(3,6)
print(A)
print(A.argmax(axis=0))
print(A.argmax(axis=1)) #position[0 1 2 3]
print(A.argmin())

[[18.         17.23529412 16.47058824 15.70588235 14.94117647 14.17647059]
 [13.41176471 12.64705882 11.88235294 11.11764706 10.35294118  9.58823529]
 [ 8.82352941  8.05882353  7.29411765  6.52941176  5.76470588  5.        ]]
[0 0 0 0 0 0]
[0 0 0]
17


In [ ]:
#argmax
import numpy as np
A=np.array([11,23,45,26,9,24,78,25,79,36,42,64]).reshape(3,4)
print(A)
print(A.argmax(axis=0))
print(A.argmax(axis=1))
print(A.argmin())

[[11 23 45 26]
 [ 9 24 78 25]
 [79 36 42 64]]
[2 2 1 2]
[2 2 0]
4


In [ ]:
#mean,median,mode,std,varience
import numpy as np
A=np.array([1,2,3,4,5,6])
print("mean:",np.mean(A))
print("median:",np.median(A))
print("variance:",np.var(A))
print("standard deviation:",np.std(A))

mean: 3.5
median: 3.5
variance: 2.9166666666666665
standard deviation: 1.707825127659933


In [ ]:
A=np.pi #pi=180
print(A) #radians
np.rad2deg(A)

3.141592653589793


180.0

In [ ]:
A=np.array([np.pi/4,np.pi/3,np.pi/2,np.pi])
print(A)

[0.78539816 1.04719755 1.57079633 3.14159265]


In [ ]:
print(np.rad2deg(A))

[ 45.  60.  90. 180.]


In [ ]:
C=np.array([30,45,60,90,120,180])
print(np.deg2rad(C))

[0.52359878 0.78539816 1.04719755 1.57079633 2.0943951  3.14159265]


In [ ]:
#trignometry values
print("sin values")
print(np.sin(C))
print("cos values")
print(np.cos(C))
print("tan values")
print(np.tan(C))
'''print("cot values")
print(np.cot(C))
print("sec values")
print(np.sec(C))
print("cosec values")
print(np.cosec(C))'''
print(np.arcsin(1)) #sin^-1
print(np.arccos(1)) #cis^-1
print(np.arctan(1)) #tan^-1

sin values
[-0.98803162  0.85090352 -0.30481062  0.89399666  0.58061118 -0.80115264]
cos values
[ 0.15425145  0.52532199 -0.95241298 -0.44807362  0.81418097 -0.59846007]
tan values
[-6.4053312   1.61977519  0.32004039 -1.99520041  0.71312301  1.33869021]
1.5707963267948966
0.0
0.7853981633974483


In [ ]:
#hypotneuse
a=80
b=60
print(np.hypot(a,b)) #hypotneuse

100.0


In [ ]:
#searching an array
import numpy as np
A=np.array([90,34,56,13,35,56])
print(np.where(A==56)) #56 is present in two positions
print(np.where(A%2==0)) #even
print(np.where(A>50))

(array([2, 5]),)
(array([0, 1, 2, 5]),)
(array([0, 2, 5]),)


In [ ]:
A=np.array([90,3,45,84,53,27])
print(np.searchsorted(A,12)) #outputs the index of a sorted element

2


In [ ]:
A=np.array([2,3,4,5])
B=np.array([6,7,8,9])
print(np.add(A,B))
print(np.subtract(A,B))
print(np.mod(A,B))
print(np.multiply(A,B))
print(np.divmod(A,B))
print(np.sort(A))
print(np.diff(A))
print(np.setdiff1d(A,B))
print(np.intersect1d(A,B))

[ 8 10 12 14]
[-4 -4 -4 -4]
[2 3 4 5]
[12 21 32 45]
(array([0, 0, 0, 0]), array([2, 3, 4, 5]))
[2 3 4 5]
[1 1 1]
[2 3 4 5]
[]


In [ ]:

#round functions
import numpy as np
A1=np.trunc([-3.1666,3.6667])
print(A1)
A2=np.fix([-3.1666,3.6667])
print(A2)
A3=np.around(-3.1666,4)
print(A3)
A4=np.floor([-3.1666,3.6667])
print(A4)
A5=np.ceil([-3.1666,3.6667])
print(A5)

[-3.  3.]
[-3.  3.]
-3.1666
[-4.  3.]
[-3.  4.]


In [ ]:

#Rounding in array
A=np.array([4.5,-4.5])
print(np.fix(A))
print(np.floor(A))
print(np.around(A))
print(np.ceil(A))

[ 4. -4.]
[ 4. -5.]
[ 4. -4.]
[ 5. -4.]


In [ ]:
A=np.array([3,4,16,19,10])
print(np.cumsum(A))
print(np.cumprod(A))

[ 3  7 23 42 52]
[    3    12   192  3648 36480]


In [ ]:

#finding LCM and gcd
A=np.array([45,65,30])
print(np.lcm.reduce(A))
print(np.gcd.reduce(A))

1170
5


In [ ]:
#matrix inverse
A=np.array([[1,2],[3,4]])
print(np.linalg.inv(A)) #matrix A^-1

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
#random package
from numpy import random as rd
A=rd.rand() #n #default limit 0 to 0.99
print(A)

0.7730262493368879


In [ ]:
#random
A=rd.rand(10) #limit
print(A)

[0.67412351 0.34942212 0.04902278 0.4440402  0.88708095 0.51604325
 0.80733008 0.03912963 0.72220761 0.17464483]


In [ ]:
#random
A=rd.randint(4) #limit is 0,1,2,3
print(A)
B=rd.randint(5,size=3)
print(B)
C=rd.randint(50,size=(2,3))

1
[0 1 0]


In [ ]:
#outer,inner,cross
import numpy as np
A=np.array([1,2,3])
B=np.array([4,5,6])
print(np.inner(A,B))
print(np.outer(A,B)) #1x(4,5,6) 2x(4,5,6) 3x(4,5,6)
print(np.cross(A,B))

32
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
[-3  6 -3]
